console.log("Hello GitHub")
console.log("chào bạn")
console.log("Trung tâm")
console.log("Trung tâm bảo hành")
console.log("Ngay Tet Que Em")
<<<<<<< HEAD
console.log("Các bài hát Việt Nam")
console.log("TẾT")
console.log("TẾT")
console.log("TẾT")
=======
console.log("Xuan Chien Khu")

console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")
console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")
console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")
console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")
console.log("Qua đi ")
console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")
console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")

console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")
console.log("Qua đi ")
console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")
console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")

console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")
console.log("Qua đi ")
console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")
console.log("Qua Tết")
console.log("Hết tết rồi ")
console.log("Cày bừa tiếp thôi ")
console.log("ok ok ok")
console.log("Qua đi ")

>>>>>>> 92833628f537791e156b9d9bb22d0b2f03f3a80c
